"""packaging\\downloads.iss — the installer's download list, generated from
the two locks (DISTRIBUTION_PLAN.md 10.4, 2026-09-19).

    python dev/make_downloads_iss.py            rewrite packaging\\downloads.iss
    python dev/make_downloads_iss.py --check    exit 1 when the committed file
                                                is not what the locks say

The installer downloads what the first-run wizard's computer page used to
(the owner's word, 2026-09-19: "everything comes the moment I install; no
installation page"): the Hebrew model, and — with an NVIDIA card — its
libraries and the English detector, and the Recording pack. Pascal Script
cannot read JSON, so the rows the [Code] section needs come from here as
plain functions: one row per file (item, the path under the data folder,
the URL, the SHA-256 the download is checked against, the size), and per
item the size line, the marker that says it is already on this PC, the
words that marker must hold, and the licence links the page shows. The
file is committed beside DeskIT.iss so ISCC needs no Python first;
release.yml and build_local.ps1 run `--check` so a lock that moved
without this file fails the build instead of shipping a stale list.

Nothing here is bundled: the installer fetches from the same URLs, with
the same hashes, that models.py and packs.py use (D13, D24), and only
with the person's tick. `main.py --adopt-downloads` then hashes and
completes what landed.
"""
from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "packaging" / "downloads.iss"
HUB = "https://huggingface.co"

#: The items, in the order the page lists them and the installer downloads.
ITEMS = ("model", "detector", "gpu", "recording")


def human(n: int) -> str:
    """steps.human without importing the app: 1.62 GB, 28 MB."""
    n = int(n)
    if n >= 1_000_000_000:
        return f"{n / 1e9:.2f} GB"
    if n >= 1_000_000:
        return f"{n / 1e6:.0f} MB"
    return f"{n / 1e3:.1f} kB"


def _pas(s: str) -> str:
    """A Pascal string literal."""
    return "'" + s.replace("'", "''") + "'"


def _model_names() -> tuple[str, str]:
    data = tomllib.loads((REPO / "defaults.toml").read_text("utf-8"))
    local = data.get("local", {})
    return str(local.get("model", "")), str(local.get("english_model", ""))


def items() -> dict[str, dict]:
    """Every item with its rows and its page facts, from the locks."""
    models = json.loads((REPO / "models.lock").read_text("utf-8"))["models"]
    packs = json.loads((REPO / "packs.lock").read_text("utf-8"))["packs"]
    hebrew, english = _model_names()
    out: dict[str, dict] = {}
    for item, repo in (("model", hebrew), ("detector", english)):
        e = models[repo]
        folder = repo.replace("/", "--")
        out[item] = {
            "rows": [(f"models\\{folder}\\{name}",
                      f"{HUB}/{repo}/resolve/{e['revision']}/{name}",
                      f["sha256"], int(f["size"]))
                     for name, f in e["files"].items()],
            "bytes": int(e["bytes"]),
            "marker": f"models\\{folder}\\.complete",
            "stamps": [e["revision"]],
            "licenses": [(f"{repo} ({e.get('license', '')})", f"{HUB}/{repo}")],
        }
    for item in ("gpu", "recording"):
        p = packs[item]
        out[item] = {
            "rows": [(f"packs\\{item}\\wheels\\{w['filename']}", w["url"],
                      w["sha256"], int(w["size"])) for w in p["wheels"]],
            "bytes": int(p["bytes"]),
            "marker": f"packs\\{item}\\packs.lock",
            # the record packs.install writes: {"versions": {"name": "version", ...}}
            "stamps": [f'"{w["name"]}": "{w["version"]}"' for w in p["wheels"]],
            "licenses": [tuple(pair) for pair in p["licenses"]],
        }
    return out


def render(table: dict[str, dict]) -> str:
    rows = [(item, *row) for item in ITEMS for row in table[item]["rows"]]
    lines = [
        "{ GENERATED by dev\\make_downloads_iss.py from models.lock, packs.lock and",
        "  defaults.toml (local.model, local.english_model) - do not edit; run the",
        "  script, or `--check` to see whether this file is what the locks say.",
        "  What DeskIT.iss downloads with the person's tick (10.4), one row per",
        "  file: item, the path under the data folder, the URL, the SHA-256 the",
        "  download is checked against, the size. Nothing here is bundled. }",
        "",
        f"function DlItems: String; begin Result := {_pas('|'.join(ITEMS))}; end;",
        f"function DlCount: Integer; begin Result := {len(rows)}; end;",
        "",
        "function DlRow(I: Integer): String;",
        "begin",
        "  case I of",
    ]
    for i, (item, rel, url, sha, size) in enumerate(rows):
        lines.append(f"    {i}: Result := {_pas('|'.join((item, rel, url, sha, str(size))))};")
    lines += ["  else", "    Result := '';", "  end;", "end;", ""]

    def lookup(name: str, key, doc: str) -> None:
        lines.append(f"{{ {doc} }}")
        lines.append(f"function {name}(Item: String): String;")
        lines.append("begin")
        lines.append("  Result := '';")
        for n, item in enumerate(ITEMS):
            word = "if" if n == 0 else "else if"
            lines.append(f"  {word} Item = {_pas(item)} then Result := {_pas(key(table[item]))}")
        lines[-1] += ";"
        lines.extend(["end;", ""])

    lookup("DlBytes", lambda t: str(t["bytes"]),
           "The item's size in bytes, as a string (StrToInt64 - the sum is past an Integer)")
    lookup("DlHuman", lambda t: human(t["bytes"]), "The size the page shows")
    lookup("DlMarker", lambda t: t["marker"],
           "The file under the data folder whose presence says the item is already on this PC")
    lookup("DlStamps", lambda t: "|".join(t["stamps"]),
           "The words the marker must hold for that to be true (the lock's revision; each wheel's version)")
    lookup("DlLicenses", lambda t: "|".join(f"{title}>{url}" for title, url in t["licenses"]),
           "The licence links the page shows for the item: Title>URL, one per bar")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    text = render(items())
    current = OUT.read_text("utf-8") if OUT.exists() else None
    if current == text:
        print(f"{OUT.relative_to(REPO)}: fresh")
        return 0
    if check:
        print(f"{OUT.relative_to(REPO)}: STALE - run python dev/make_downloads_iss.py")
        return 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"{OUT.relative_to(REPO)}: written")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
