{ GENERATED by dev\make_downloads_iss.py from models.lock, packs.lock and
  defaults.toml (local.model, local.english_model) - do not edit; run the
  script, or `--check` to see whether this file is what the locks say.
  What DeskIT.iss downloads with the person's tick (10.4), one row per
  file: item, the path under the data folder, the URL, the SHA-256 the
  download is checked against, the size. Nothing here is bundled. }

function DlItems: String; begin Result := 'model|detector|gpu|recording'; end;
function DlCount: Integer; begin Result := 14; end;

function DlRow(I: Integer): String;
begin
  case I of
    0: Result := 'model|models\ivrit-ai--whisper-large-v3-turbo-ct2\config.json|https://huggingface.co/ivrit-ai/whisper-large-v3-turbo-ct2/resolve/72ad623a37947395efcc3933132353790e5a12f5/config.json|c805eff43fc2a1d00d5cfa315e4b2230895f34994257c185959808a116e7c4f0|1405';
    1: Result := 'model|models\ivrit-ai--whisper-large-v3-turbo-ct2\model.bin|https://huggingface.co/ivrit-ai/whisper-large-v3-turbo-ct2/resolve/72ad623a37947395efcc3933132353790e5a12f5/model.bin|db2a2265aa012c16c7db9edda3d699c99f984efdd3f2e22a72a8ce7e9720f3a2|1617884968';
    2: Result := 'model|models\ivrit-ai--whisper-large-v3-turbo-ct2\preprocessor_config.json|https://huggingface.co/ivrit-ai/whisper-large-v3-turbo-ct2/resolve/72ad623a37947395efcc3933132353790e5a12f5/preprocessor_config.json|654cf18d3e163b948ceaf9766da56ce0b52de265d58673cf61c9376f126bd499|357';
    3: Result := 'model|models\ivrit-ai--whisper-large-v3-turbo-ct2\tokenizer.json|https://huggingface.co/ivrit-ai/whisper-large-v3-turbo-ct2/resolve/72ad623a37947395efcc3933132353790e5a12f5/tokenizer.json|297b13372ac43916285644fb9687add3cc62ee2a1adb60da3dc25cc94c1871fd|2710337';
    4: Result := 'model|models\ivrit-ai--whisper-large-v3-turbo-ct2\vocabulary.json|https://huggingface.co/ivrit-ai/whisper-large-v3-turbo-ct2/resolve/72ad623a37947395efcc3933132353790e5a12f5/vocabulary.json|c69260f2ab26d659b7c398f9a2b2b48ed0df16c3b47d7326782fd9cba71690c1|1068114';
    5: Result := 'detector|models\deepdml--faster-whisper-large-v3-turbo-ct2\config.json|https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2/resolve/4df90f75321148c3a29a9e2351b7ddf8f5b115a8/config.json|b0253ea6c0d3bea6b1e19e91a02acfd3b53f4467362efcb5a3e6b16c9b3a9b7e|2263';
    6: Result := 'detector|models\deepdml--faster-whisper-large-v3-turbo-ct2\model.bin|https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2/resolve/4df90f75321148c3a29a9e2351b7ddf8f5b115a8/model.bin|e76620f83d5f5b69efd3d87e3dc180c1bd21df9fbebacfd4335e5e1efcc018da|1617884929';
    7: Result := 'detector|models\deepdml--faster-whisper-large-v3-turbo-ct2\preprocessor_config.json|https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2/resolve/4df90f75321148c3a29a9e2351b7ddf8f5b115a8/preprocessor_config.json|7ccc62c6f2765af1f3b46c00c9b5894426835a05021c8b9c01eecb6dfb542711|340';
    8: Result := 'detector|models\deepdml--faster-whisper-large-v3-turbo-ct2\tokenizer.json|https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2/resolve/4df90f75321148c3a29a9e2351b7ddf8f5b115a8/tokenizer.json|297b13372ac43916285644fb9687add3cc62ee2a1adb60da3dc25cc94c1871fd|2710337';
    9: Result := 'detector|models\deepdml--faster-whisper-large-v3-turbo-ct2\vocabulary.json|https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2/resolve/4df90f75321148c3a29a9e2351b7ddf8f5b115a8/vocabulary.json|c69260f2ab26d659b7c398f9a2b2b48ed0df16c3b47d7326782fd9cba71690c1|1068114';
    10: Result := 'gpu|packs\gpu\wheels\nvidia_cublas_cu12-12.9.2.10-py3-none-win_amd64.whl|https://files.pythonhosted.org/packages/20/e2/fc9a0e985249d873150276d5afb02e39a66817fedbf1a385724393e505ed/nvidia_cublas_cu12-12.9.2.10-py3-none-win_amd64.whl|623f43027d40d44ceadf0043f002bd25cf353e8f13ce90b9a87057019f560661|553162896';
    11: Result := 'gpu|packs\gpu\wheels\nvidia_cudnn_cu12-9.24.0.43-py3-none-win_amd64.whl|https://files.pythonhosted.org/packages/29/28/2c9a2a97a8b3fedcf74a14f38fd5edfae12274380a829fdc6b16ce29be4c/nvidia_cudnn_cu12-9.24.0.43-py3-none-win_amd64.whl|cbd41a0ab084422c936dc9fb2fc89be5ea9a85bc421c6f23d0243bdfc945fbef|737103728';
    12: Result := 'gpu|packs\gpu\wheels\nvidia_cuda_nvrtc_cu12-12.9.86-py3-none-win_amd64.whl|https://files.pythonhosted.org/packages/52/de/823919be3b9d0ccbf1f784035423c5f18f4267fb0123558d58b813c6ec86/nvidia_cuda_nvrtc_cu12-12.9.86-py3-none-win_amd64.whl|72972ebdcf504d69462d3bcd67e7b81edd25d0fb85a2c46d3ea3517666636349|76408187';
    13: Result := 'recording|packs\recording\wheels\av-18.0.0-cp311-abi3-win_amd64.whl|https://files.pythonhosted.org/packages/11/85/0f121ff43dc5a70696676c98a8f1674e2fa787614c2abaacb15fa1a9bc99/av-18.0.0-cp311-abi3-win_amd64.whl|aaf4d354d2beaa6651e4f92e54409a578bde64f79c0beef9a30b388d06f7c629|27556236';
  else
    Result := '';
  end;
end;

{ The item's size in bytes, as a string (StrToInt64 - the sum is past an Integer) }
function DlBytes(Item: String): String;
begin
  Result := '';
  if Item = 'model' then Result := '1621665181'
  else if Item = 'detector' then Result := '1621665983'
  else if Item = 'gpu' then Result := '1366674811'
  else if Item = 'recording' then Result := '27556236';
end;

{ The size the page shows }
function DlHuman(Item: String): String;
begin
  Result := '';
  if Item = 'model' then Result := '1.62 GB'
  else if Item = 'detector' then Result := '1.62 GB'
  else if Item = 'gpu' then Result := '1.37 GB'
  else if Item = 'recording' then Result := '28 MB';
end;

{ The file under the data folder whose presence says the item is already on this PC }
function DlMarker(Item: String): String;
begin
  Result := '';
  if Item = 'model' then Result := 'models\ivrit-ai--whisper-large-v3-turbo-ct2\.complete'
  else if Item = 'detector' then Result := 'models\deepdml--faster-whisper-large-v3-turbo-ct2\.complete'
  else if Item = 'gpu' then Result := 'packs\gpu\packs.lock'
  else if Item = 'recording' then Result := 'packs\recording\packs.lock';
end;

{ The words the marker must hold for that to be true (the lock's revision; each wheel's version) }
function DlStamps(Item: String): String;
begin
  Result := '';
  if Item = 'model' then Result := '72ad623a37947395efcc3933132353790e5a12f5'
  else if Item = 'detector' then Result := '4df90f75321148c3a29a9e2351b7ddf8f5b115a8'
  else if Item = 'gpu' then Result := '"nvidia-cublas-cu12": "12.9.2.10"|"nvidia-cudnn-cu12": "9.24.0.43"|"nvidia-cuda-nvrtc-cu12": "12.9.86"'
  else if Item = 'recording' then Result := '"av": "18.0.0"';
end;

{ The licence links the page shows for the item: Title>URL, one per bar }
function DlLicenses(Item: String): String;
begin
  Result := '';
  if Item = 'model' then Result := 'ivrit-ai/whisper-large-v3-turbo-ct2 (apache-2.0)>https://huggingface.co/ivrit-ai/whisper-large-v3-turbo-ct2'
  else if Item = 'detector' then Result := 'deepdml/faster-whisper-large-v3-turbo-ct2 (mit)>https://huggingface.co/deepdml/faster-whisper-large-v3-turbo-ct2'
  else if Item = 'gpu' then Result := 'NVIDIA CUDA EULA>https://docs.nvidia.com/cuda/eula/index.html|cuDNN SLA>https://docs.nvidia.com/deeplearning/cudnn/backend/latest/reference/eula.html'
  else if Item = 'recording' then Result := 'PyAV licence (BSD-3)>https://github.com/PyAV-Org/PyAV/blob/main/LICENSE.txt|FFmpeg licence (this build is GPL: x264, x265)>https://ffmpeg.org/legal.html';
end;
